#!/bin/bash
color="\e[1;33m"
clear="\e[m"
# figlet  -f chunky "ASRock" 
echo -e "${color} _______ _______ ______              __    
|   _   |     __|   __ \.-----.----.|  |--.
|       |__     |      <|  _  |  __||    < 
|___|___|_______|___|__||_____|____||__|__|"
echo -e ${clear}