#!/bin/zsh
#
# GREETER SCRIPT FOR ARCHLINUX SRV
# https://github.com/Gazeka74/archserver-motd/blob/master/arch-greeter

#########################################
#
#		VARIABLES
#
#########################################

# Hostname
host="$(cat /etc/hostname)"

# Kernel information
kernel="$(uname -sr)"

# Uptime
uptime="$(uptime -p | sed 's/up //')"

# Numbers of packages installed
packages="$(pacman -Q | wc -l)"

# Numbers of updates pending
updates_count="$(checkupdates | wc -l)"

# Numbers of IP bannedi

# f2b="$(sudo fail2ban-client status sshd | grep 'Currently banned' | rev | cut -f 1 | rev)"
# banned="$f2b IP banned"	
# f2b="$(sudo fail2ban-client status sshd | grep 'Currently banned' | rev | cut -f 1 | rev)"
banned="IP banned"		

# Text to be displayed
if (( $updates_count > 0 )); then
	updates="$updates_count updates pending"
else
	updates="$updates_count update pending" 
fi

## Filesystem
# Number of '-' to be displayed on the filesystem occupation
number=30

# 3T self
read self_a self_s self_m self_pcent<<< "$(df -h --output=avail,size,target,pcent /dev/sda1 | tail -1)" 

# 8T nas
read nas_a nas_s nas_m nas_pcent<<< "$(df -h --output=avail,size,target,pcent /dev/sdb1 | tail -1)"

# /boot
read boot_a boot_s boot_m boot_pcent <<< "$(df -h --output=avail,size,target,pcent /dev/sdc1 | tail -1)"

# /
read root_a root_s root_m root_pcent<<< "$(df -h --output=avail,size,target,pcent /dev/sdc2 | tail -1)"

## Colors
bold="\033[01;1m"
black="\033[01;36m"
red="\033[01;31m"
green="\033[01;32m"
yellow="\033[01;33m"
blue="\033[01;34m"
magenta="\033[01;35m"
cyan="\033[01;36m"
white="\033[01;37m"
reset="\033[0m"

beg="${c1} ${c0}"			# in front of information
c0="${reset}${blue}${bold}"		# logo + text 1 color
c1="${reset}${white}${bold}"		# text 2 color
upd_color=""				# updates based on amount

#########################################
#
#		FUNCTIONS
#
#########################################

# Displays a progression bar of the FS depending on the available space and the total space
# $PARAM1 = name of the FS
# $PARAM2 = available size
# $PARAM3 = total size
# $PARAM4 = percentage used
# $PARAM5 = Number of - to be displayed
trace_fs () {
	temp1="${4%?}"			# Remove last character
	temp2=$(($temp1*$5/100))	# Number of #
	str="["				# Initiate

	# Add a color to the output
	if (($temp1 > 75)); then
		str+="${red}"
	elif (($temp1 > 50)); then
		str+="${yellow}"
	elif (($temp1 > 25)); then
		str+="${green}"
	else 
		str+="${white}"
	fi
	# Fill with '#'
	for i in $(seq 1 $temp2)
	do
		str+="#"
	done

	# reset the color
	str+="${white}"

	# Fill with '-'
	for i in $(seq $temp2 $5)
	do
		str+="-"
	done
	str+="]"
	echo $str
}

sda1=$(trace_fs $self_m $self_a $self_s $self_pcent $number)
sdb1=$(trace_fs $nas_m $nas_a $nas_s $nas_pcent $number)
sdc1=$(trace_fs $boot_m $boot_a $boot_s $boot_pcent $number)
sdc2=$(trace_fs $root_m $root_a $root_s $root_pcent $number)


#########################################
#
#		PROCESSING		
#
#########################################

# Setting updates color 
if (( $updates_count > 15 )); then
	upd_color="${reset}${red}"
elif (( $updates_count > 5 )); then
	upd_color="${reset}${yellow}"
else	
	upd_color="${reset}${white}"
fi

echo "
${c0}                    -\`
${c0}                   .o+\`
${c0}                  \`ooo/		
${c0}                 \`+oooo:		${white}               #     ${blue}| *
${c0}                \`+oooooo:		${white} a##e #%\" a#\"e 6##%  ${blue}| | |-^-. |   | \\ /
${c0}                -+oooooo+:		${white}.oOo# #   #    #  #  ${blue}| | |   | |   |  X
${c0}             \`/:-:++oooo+:		${white}%OoO# #   %#\"e #  #  ${blue}| | |   | ^._.| / \\ TM
${c0}             \`/++++/+++++++:		${white}----------------------------------------
${c0}            \`/++++++++++++++:		${beg}${USER}${reset}@${c0}${host}
${c0}           \`/+++ooooooooooooo/\`		${beg}KERNEL:	${c1}${kernel}
${c0}          ./ooosssso++osssssso+\`	${beg}UPTIME:	${c1}${uptime}
${c0}         .oossssso-\`\`\`\`/ossssss+\`	${beg}PACKAGES:	${c1}${packages}
${c0}        -osssssso.      :ssssssso.	${beg}UPDATES:	${upd_color}${updates}
${c0}       :osssssss/        osssso+++.	${beg}BANNED:	${c1}${banned}
${c0}      /ossssssss/        +ssssooo/-
${c0}    \`/ossssso+/:-        -:/+osssso+-
${c0}   \`+sso+:-\`                 \`.-/+oso:
${c0}  \`++:.                           \`-/+/
${c0}  .\`                                 \`/
${white}${bold}--------------------------------------------------------------------------------
FILESYSTEM		TOTAL	AVAIL	USED
$root_m			$root_s	$root_a	$root_pcent	${sdc2}
$boot_m			$boot_s	$boot_a	$boot_pcent	${sdc1}
$self_m	$self_s	$self_a	$self_pcent	${sda1}
$nas_m	$nas_s	$nas_a	$nas_pcent	${sdb1}
${white}${bold}--------------------------------------------------------------------------------
"
